version: '3'
services: 
    server:
        build: ./server
        ports: 
        - "8080:8080"
        volumes: 
        - ./:/app
        network_mode: "host"
        command: bash -c "make -C server/ build && ./server/bin/grpc_server"
    http_proxy:
        build: ./http_proxy
        ports:
        - "8088:8088"
        volumes:
        - ./:/app
        network_mode: "host"
        command: bash -c "make -C http_proxy/ build && ./http_proxy/bin/http_proxy"