FROM golang:1.13.4

# Set up the installation directory for go
ENV GOBIN=/go/bin
ENV GO111MODULE=on

RUN go clean --modcache
# install Goa from source
RUN go get -u goa.design/goa/v3
RUN go get -u goa.design/goa/v3/...

# get the protoc compiler 
RUN go get -d -u github.com/golang/protobuf/protoc-gen-go
RUN go install github.com/golang/protobuf/protoc-gen-go

#get some useful tools installed on the image
RUN apt update && apt upgrade -y 
RUN apt install unzip -y 


# Proceed with protoc installation
RUN wget -O /go/bin/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.10.0/protoc-3.10.0-linux-x86_64.zip
RUN unzip /go/bin/protoc.zip -d /temp
RUN cp /temp/bin/protoc /go/bin/

WORKDIR /demo-reverse-proxy

RUN go get -u golang.org/x/lint/golint